# Generated by Django 4.0.3 on 2022-03-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pakidex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='pakiName',
            new_name='personalName',
        ),
        migrations.RenameField(
            model_name='move',
            old_name='move',
            new_name='whichCard',
        ),
        migrations.RenameField(
            model_name='pakimon',
            old_name='paki',
            new_name='whichCard',
        ),
    ]
