# Generated by Django 4.0.3 on 2022-05-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakidex', '0004_card_health_card_level_card_species_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='species',
            field=models.CharField(choices=[('Bulbasaur', 'Bulbasaur'), ('Squirtle', 'Squirtle'), ('Charmander', 'Charmander'), ('Pikachu', 'Pikachu'), ('Pidgy', 'Pidgey'), ('Geodude', 'Geodude'), ('Vanillite', 'Vanillite')], default='Bulbasaur', max_length=280),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('Grass', 'Grass'), ('Water', 'Water'), ('Fire', 'Fire'), ('Ice', 'Ice'), ('Flying', 'Flying'), ('Rock', 'Rock'), ('Electric', 'Electric')], default='Grass', max_length=12),
        ),
    ]
