# Generated by Django 4.0.3 on 2022-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakidex', '0006_remove_deck_whosecard_deck_id_remove_deck_deck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='whoseCard',
            field=models.ManyToManyField(to='pakidex.card'),
        ),
    ]
