# Generated by Django 4.0.3 on 2022-05-19 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pakidex', '0007_deck_whosecard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pakimon',
        ),
    ]
